# Generated by Django 3.0.2 on 2020-04-08 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('aircraft_type', models.CharField(choices=[('GA', 'General Aviation'), ('LSA', 'Light Sport Aircraft'), ('LARGE', 'LARGE Aircraft'), ('MAV', 'Miniature UAS'), ('SUAS', 'Small Uas'), ('STUAS', 'Small Tactical UAS'), ('TUAS', 'Tactical UAS'), ('MALE', 'Medium Altitude Long Endurance UAS'), ('HALE', 'High Altitude Long Endurance UAS')], max_length=5, null=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
