"""Initial unmanned-aircraft sizing (Gundlach 2012, chapter 3)."""

from .calculate import (
    NM_LB_PER_HP_H,
    battery_mass_fraction,
    calculate_uas_sizing,
    electric_efficiency_product,
    energy_fraction_sweep,
    fuel_mass_fraction_jet,
    fuel_mass_fraction_propeller,
    propulsion_mass_fraction,
    empty_weight_check,
    takeoff_weight,
    weight_escalation_factor,
)
from .contracts import (
    BatteryPerformance,
    Energy,
    FixedWeights,
    FuelPerformance,
    JetPerformance,
    Mission,
    MissionObjective,
    Propulsion,
    PropulsionType,
    EmptyWeightCheck,
    ScalingFractions,
    SweepPoint,
    UasSizingError,
    UasSizingInputs,
    UasSizingResult,
    WeightBreakdown,
)

__all__ = [
    "NM_LB_PER_HP_H",
    "BatteryPerformance",
    "Energy",
    "FixedWeights",
    "FuelPerformance",
    "JetPerformance",
    "Mission",
    "MissionObjective",
    "Propulsion",
    "PropulsionType",
    "EmptyWeightCheck",
    "ScalingFractions",
    "SweepPoint",
    "UasSizingError",
    "UasSizingInputs",
    "UasSizingResult",
    "WeightBreakdown",
    "battery_mass_fraction",
    "calculate_uas_sizing",
    "electric_efficiency_product",
    "energy_fraction_sweep",
    "fuel_mass_fraction_jet",
    "fuel_mass_fraction_propeller",
    "propulsion_mass_fraction",
    "empty_weight_check",
    "takeoff_weight",
    "weight_escalation_factor",
]
